version: '3'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - cluster.name=ingrid
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
    # volumes:
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300